_target_: torch_implementation.language_model.GreekGPTPretrain
model:
  _target_: torch_implementation.language_model.GreekGPT
  vocab_size: 5000
  n_embed: 64
  context_len: 256
  n_blocks: 2
  n_heads: 2
  dropout: 0.2
lr: 3e-4
