_target_: torch_implementation.language_model.GreekGPTPretrain
model:
  _target_: torch_implementation.language_model.GreekGPT
  vocab_size: 5000
  n_embed: 768
  context_len: 256
  n_blocks: 10
  n_heads: 10
  dropout: 0.2
lr: 3e-4
